name: NPM Build
description: Build a Node.js project
inputs:
  repository:
    description: Repository
    required: true
  node_version:
    description: Node Version
    default: '20'
    required: false
  shell:
    description: Shell
    default: bash
    required: false

runs:
  using: composite
  steps:
    - name: Checkout Repo
      uses: actions/checkout@b4ffde6 # v4.1.1
      with:
        repository: ${{ inputs.repository }}
    - name: Setup node
      uses: actions/setup-node@60edb5d # v4.0.2
      with:
        node-version: ${{ inputs.node_version }}
        cache: npm
    - name: Install dependencies
      shell: ${{ inputs.shell }}
      run: npm ci --force
    - name: Build
      run: npm run build --if-present
      shell: ${{ inputs.shell }}
    - name: Test
      shell: ${{ inputs.shell }}
      run: npm run test --if-present
