name: Notify Slack
description: Send notification to Slack
inputs:
  channel_id:
    description: Slack Channel id or name
    default: C06PPSAV6TW #dynamo-build-notify
    required: false
  slack_bot_token:
    description: Slack Bot Token
    required: true

runs:
  using: composite
  steps: 
    - name: Set user tag
      id: set_user_tag
      shell: bash
      run: |
        slack_id=$(curl "https://slack.com/api/users.lookupByEmail?token=${{ inputs.slack_bot_token }}&email=${{ github.event.head_commit.author.email }}" | jq -r '.user.id')
        if [[ -z $slack_id || $slack_id == "null" ]]; then
          user_tag="<mailto:${{ github.event.head_commit.author.email }}|${{ github.event.head_commit.author.name }}>"
        else
          user_tag="<@$slack_id>"
        fi
        echo "USER_TAG=$user_tag" >> $GITHUB_OUTPUT
    - name: Set message
      id: set_message
      shell: bash
      run: |
        job_status="${{ job.status }}"
        run_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        run_title="${{ github.repository }} » ${{ github.ref_name }} » ${{ github.workflow }}"
        echo "MESSAGE_TITLE=*${job_status^^}*: <$run_url|$run_title>" >> $GITHUB_OUTPUT
    - name: Send message
      uses: slackapi/slack-github-action@6c661ce58804a1a20f6dc5fbee7f0381b469e001 # v1.25.0
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
      with:
        channel-id: ${{ inputs.channel_id }}
        payload: |
          {
            "text": "${{ steps.set_message.outputs.MESSAGE_TITLE }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ steps.set_message.outputs.MESSAGE_TITLE }}"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Commit:*\n<${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Author:*\n${{ steps.set_user_tag.outputs.USER_TAG }}"
                  }
                ]
              }
            ]
          }
