name: Notify Slack
description: Send notification to Slack
inputs:
  channel_id:
    description: Slack Channel id or name
    default: C06PPSAV6TW #dynamo-build-notify
    required: false
  slack_bot_token:
    description: Slack Bot Token
    required: true
  include_commit_info:
    description: Include commit information slack notification
    default: 'false'
    required: false

runs:
  using: composite
  steps:
    - name: Set commit info
      id: set_commit_info
      if: ${{ inputs.include_commit_info }} == 'true'
      shell: bash
      run: |
        commit_sha=${{ github.event.pull_request.head.sha || github.sha }}
        commit_message=$(git log -n 1 --pretty=format:%s $commit_sha)
        commit_author_name=$(git log -n 1 --pretty=format:%aN $commit_sha)
        commit_author_email=$(git log -n 1 --pretty=format:%aE $commit_sha)
        commit_url="${{ github.server_url }}/${{ github.repository }}/commit/$commit_sha"

        api_url="https://slack.com/api/users.lookupByEmail?token=${{ inputs.slack_bot_token }}&email=$commit_author_email"
        slack_id=$(curl $api_url | jq -r '.user.id')
        if [[ -z $slack_id || $slack_id == "null" ]]; then
          user_tag="<mailto:$commit_author_email|$commit_author_name>"
        else
          user_tag="<@$slack_id>"
        fi

        echo "COMMIT_INFO=*Commit:*\n<$commit_url|$commit_message>" >> $GITHUB_OUTPUT
        echo "AUTHOR_INFO=*Author:*\n$user_tag" >> $GITHUB_OUTPUT
    - name: Create payload
      shell: python
      run: |
        import json
        import os

        job_status = "${{ job.status }}".upper()
        run_url = "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        run_title = "${{ github.repository }} » ${{ github.ref_name }} » ${{ github.workflow }}"
        message_title = f"*{job_status}*: <{run_url}|{run_title}>"

        payload = {}
        blocks = []

        payload['text'] = message_title
        blocks.append({
          "type": "section",
          "text": {
            "type": "mrkdwn",
            "text": message_title
          }
        })

        if "${{ inputs.include_commit_info }}" == 'true':
          blocks.append({
            "type": "section",
            "fields": [
              {
                "type": "mrkdwn",
                "text": "${{ steps.set_commit_info.outputs.COMMIT_INFO }}"
              },
              {
                "type": "mrkdwn",
                "text": "${{ steps.set_commit_info.outputs.AUTHOR_INFO }}"
              }
            ]
          })

        with open('payload.json', 'w') as f:
          json.dump(payload, f)
    - name: Send message
      uses: slackapi/slack-github-action@6c661ce58804a1a20f6dc5fbee7f0381b469e001 # v1.25.0
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
      with:
        channel-id: ${{ inputs.channel_id }}
        payload-file-path: payload.json
