name: GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.x
      - name: Create cache id
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Cache dependencies
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 #v5.0.3
        with:
          key: mkdocs-${{ env.cache_id }}
          path: .cache
          restore-keys: mkdocs-
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Configure Git Credentials
        run: |
          git config --local user.email "dynamo@autodesk.com"
          git config --local user.name "Dynamo GitHub Actions[bot]"
      - name: Deploy to GitHub pages
        run: mkdocs gh-deploy --force
