name: GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.x
      - name: Create cache id
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Cache dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae #v5.0.5
        with:
          key: mkdocs-${{ env.cache_id }}
          path: .cache
          restore-keys: mkdocs-
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Configure Git Credentials
        run: |
          git config --local user.email "dynamo@autodesk.com"
          git config --local user.name "Dynamo GitHub Actions[bot]"
      - name: Deploy to GitHub pages
        run: mkdocs gh-deploy --force
