name: GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.x
      - name: Create cache id
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Cache dependencies
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 #v4.2.4
        with:
          key: mkdocs-${{ env.cache_id }}
          path: .cache
          restore-keys: mkdocs-
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Configure Git Credentials
        run: |
          git config --local user.email "dynamo@autodesk.com"
          git config --local user.name "Dynamo GitHub Actions[bot]"
      - name: Deploy to GitHub pages
        run: mkdocs gh-deploy --force
