name: GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Setup python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: 3.x
      - name: Create cache id
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Cache dependencies
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 #v4.0.2
        with:
          key: mkdocs-${{ env.cache_id }}
          path: .cache
          restore-keys: mkdocs-
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Configure Git Credentials
        run: |
          git config --local user.email "dynamo@autodesk.com"
          git config --local user.name "Dynamo GitHub Actions[bot]"
      - name: Deploy to GitHub pages
        run: mkdocs gh-deploy --force
