name: Greeting

on:
  workflow_call:
    inputs:
      message:
        description: Message
        default: World
        required: false
        type: string

jobs:
  greeting:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello, ${{ inputs.message }}!"
