name: Greeting (Action)

on:
  push:
    paths:
      - actions/greeting/action.yml
      - .github/workflows/greeting_action.yml
  workflow_dispatch:

jobs:
  greeting:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        id: greeting
        uses: DynamoDS/workflows/actions/greeting@master
        with:
          message: World
      - name: Random number
        run: echo "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.greeting.outputs.number }}
      - name: Date
        run: date
