name: Greeting (Workflow)

on:
  push:
    paths:
      - .github/workflows/greeting.yml
      - .github/workflows/greeting_workflow.yml
  workflow_dispatch:

jobs:
  greeting:
    name: Greeting
    uses: DynamoDS/workflows/.github/workflows/greeting.yml@master
    with:
      message: World
