name: MSBuild (Workflow)

on:
  push:
    paths:
      - .github/workflows/msbuild.yml
      - .github/workflows/msbuild_workflow.yml
  workflow_dispatch:

jobs:
  msbuild:
    name: MSBuild
    uses: DynamoDS/workflows/.github/workflows/msbuild.yml@master
    with:
      runner: windows-latest
      repository: DynamoDS/Dynamo
      dotnet_version: 8.0.x
      solution_path: src\Dynamo.All.sln
      build_configuration: Release
      runtime_identifier: win-x64
