name: Notify Slack (Action)

on:
  push:
    paths:
      - .github/actions/notify_slack/action.yml
      - .github/workflows/notify_slack_action.yml
  workflow_dispatch:

jobs:
  notify_slack:
    name: Notify Slack
    runs-on: ubuntu-latest
    steps: 
      - name: Notify Slack
        uses: DynamoDS/actions/notify_slack@feature/notify_slack
        with:
          slack_bot_token: ${{ secrets.DYNAMO_SLACK_NOTIFICATIONS_BOT_TOKEN }}
