name: NPM Build (Workflow)

on:
  push:
    paths:
      - .github/workflows/npm_build.yml
      - .github/workflows/npm_build_workflow.yml
  workflow_dispatch:

jobs:
  npm_build:
    name: NPM Build
    uses: DynamoDS/workflows/.github/workflows/npm_build.yml@master
    with:
      runner: ubuntu-latest
      repository: DynamoDS/SplashScreen
      node_version: 20
